import os
from contextlib import contextmanager

import psycopg
from psycopg.rows import dict_row

CONFIG_CACHE_VERSION_KEY = "__config_generation__"


def get_connection():
    return psycopg.connect(
        host=os.environ["POSTGRES_HOST"],
        port=os.environ["POSTGRES_PORT"],
        dbname=os.environ["POSTGRES_DB"],
        user=os.environ["POSTGRES_USER"],
        password=os.environ["POSTGRES_PASSWORD"],
        row_factory=dict_row,
    )


@contextmanager
def db_session():
    conn = get_connection()
    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def init_db():
    with db_session() as conn:
        # Serializa a inicialização para evitar corrida entre workers.
        conn.execute("SELECT pg_advisory_lock(314159265358979)")
        conn.execute("""
            CREATE TABLE IF NOT EXISTS configuracao (
                chave TEXT PRIMARY KEY,
                valor TEXT NOT NULL
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS servico (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nome TEXT NOT NULL,
                descricao TEXT NOT NULL DEFAULT '',
                preco NUMERIC(10, 2) NOT NULL,
                duracao_minutos INTEGER NOT NULL,
                ativo BOOLEAN NOT NULL DEFAULT TRUE
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS profissional (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nome TEXT NOT NULL,
                ativo BOOLEAN NOT NULL DEFAULT TRUE
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS profissional_servico (
                profissional_id INTEGER NOT NULL,
                servico_id INTEGER NOT NULL,
                PRIMARY KEY (profissional_id, servico_id),
                FOREIGN KEY (profissional_id) REFERENCES profissional(id) ON DELETE CASCADE,
                FOREIGN KEY (servico_id) REFERENCES servico(id) ON DELETE CASCADE
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS agendamento (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                cliente_nome TEXT NOT NULL,
                cliente_telefone TEXT NOT NULL,
                servico_id INTEGER NOT NULL,
                profissional_id INTEGER NOT NULL,
                data TEXT NOT NULL,
                hora TEXT NOT NULL,
                criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                profissional_nome_snapshot TEXT,
                FOREIGN KEY (servico_id) REFERENCES servico(id),
                FOREIGN KEY (profissional_id) REFERENCES profissional(id)
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS agendamento_servico (
                agendamento_id INTEGER NOT NULL,
                servico_id INTEGER NOT NULL,
                nome_servico TEXT,
                preco_unitario NUMERIC(10, 2),
                duracao_minutos INTEGER,
                PRIMARY KEY (agendamento_id, servico_id),
                FOREIGN KEY (agendamento_id) REFERENCES agendamento(id) ON DELETE CASCADE,
                FOREIGN KEY (servico_id) REFERENCES servico(id)
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS admin (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                usuario TEXT NOT NULL UNIQUE,
                senha_hash TEXT NOT NULL,
                senha_inicial_alterada BOOLEAN NOT NULL DEFAULT FALSE,
                email TEXT,
                nome_responsavel TEXT
            )
        """)

        # Compatibilidade com bancos existentes: adiciona o status sem perder dados.
        conn.execute("""
            ALTER TABLE agendamento
            ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'agendado'
        """)

        # Compatibilidade: adiciona coluna senha_inicial_alterada se não existir.
        conn.execute("""
            ALTER TABLE admin
            ADD COLUMN IF NOT EXISTS senha_inicial_alterada BOOLEAN NOT NULL DEFAULT FALSE
        """)

        # Compatibilidade: adiciona coluna email em admin se não existir.
        conn.execute("""
            ALTER TABLE admin
            ADD COLUMN IF NOT EXISTS email TEXT
        """)

        # Compatibilidade: adiciona coluna nome_responsavel em admin se não existir.
        conn.execute("""
            ALTER TABLE admin
            ADD COLUMN IF NOT EXISTS nome_responsavel TEXT
        """)

        # Tabela de tokens de recuperação de senha (expiráveis e uso único)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS admin_token_recuperacao (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                admin_id INTEGER NOT NULL REFERENCES admin(id) ON DELETE CASCADE,
                token_hash TEXT NOT NULL UNIQUE,
                expira_em TIMESTAMP WITH TIME ZONE NOT NULL,
                usado BOOLEAN NOT NULL DEFAULT FALSE,
                criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
        """)

        # Compatibilidade: adiciona coluna ativo em servico se não existir.
        conn.execute("""
            ALTER TABLE servico
            ADD COLUMN IF NOT EXISTS ativo BOOLEAN NOT NULL DEFAULT TRUE
        """)

        conn.execute("""
            ALTER TABLE servico
            ADD COLUMN IF NOT EXISTS descricao TEXT NOT NULL DEFAULT ''
        """)

        conn.execute("""
            ALTER TABLE agendamento
            ADD COLUMN IF NOT EXISTS profissional_nome_snapshot TEXT
        """)

        conn.execute("""
            ALTER TABLE agendamento_servico
            ADD COLUMN IF NOT EXISTS nome_servico TEXT
        """)
        conn.execute("""
            ALTER TABLE agendamento_servico
            ADD COLUMN IF NOT EXISTS preco_unitario NUMERIC(10, 2)
        """)
        conn.execute("""
            ALTER TABLE agendamento_servico
            ADD COLUMN IF NOT EXISTS duracao_minutos INTEGER
        """)

        conn.execute("""
            UPDATE agendamento_servico AS ags
            SET nome_servico = COALESCE(ags.nome_servico, s.nome),
                preco_unitario = COALESCE(ags.preco_unitario, s.preco),
                duracao_minutos = COALESCE(ags.duracao_minutos, s.duracao_minutos)
            FROM servico AS s
            WHERE s.id = ags.servico_id
              AND (
                  ags.nome_servico IS NULL
                  OR ags.preco_unitario IS NULL
                  OR ags.duracao_minutos IS NULL
              )
        """)

        conn.execute("""
            UPDATE agendamento AS a
            SET profissional_nome_snapshot = p.nome
            FROM profissional AS p
            WHERE p.id = a.profissional_id
              AND a.profissional_nome_snapshot IS NULL
        """)

        conn.execute("""
            CREATE INDEX IF NOT EXISTS idx_agendamento_profissional_data_status
            ON agendamento (profissional_id, data, status)
        """)

        # Migra a relação legada de serviço único para a nova relação.
        conn.execute("""
            INSERT INTO agendamento_servico (agendamento_id, servico_id)
            SELECT id, servico_id
            FROM agendamento
            WHERE servico_id IS NOT NULL
            ON CONFLICT (agendamento_id, servico_id) DO NOTHING
        """)

        conn.execute("""
            UPDATE agendamento_servico AS ags
            SET nome_servico = COALESCE(ags.nome_servico, s.nome),
                preco_unitario = COALESCE(ags.preco_unitario, s.preco),
                duracao_minutos = COALESCE(ags.duracao_minutos, s.duracao_minutos)
            FROM servico AS s
            WHERE s.id = ags.servico_id
              AND (
                  ags.nome_servico IS NULL
                  OR ags.preco_unitario IS NULL
                  OR ags.duracao_minutos IS NULL
              )
        """)

        seed_configuracao_padrao(conn)
        conn.execute(
            """
            INSERT INTO configuracao (chave, valor)
            VALUES (%s, '0')
            ON CONFLICT (chave) DO NOTHING
            """,
            (CONFIG_CACHE_VERSION_KEY,),
        )
        seed_data(conn)


def seed_configuracao_padrao(conn):
    """Insere configurações padrão apenas se a tabela estiver vazia."""
    count = conn.execute("SELECT COUNT(*) AS c FROM configuracao").fetchone()["c"]
    if count == 0:
        from datetime import time
        configuracoes = [
            ("nome_estabelecimento", "Minha Empresa"),
            ("telefone_estabelecimento", ""),
            ("endereco_estabelecimento", ""),
            ("nome_publico", "AllLogic Scheduler"),
            ("dias_antecedencia_agendamento", "14"),
            ("horario_abertura", "09:00"),
            ("horario_fechamento", "19:00"),
            ("intervalo_slot_minutos", "30"),
            ("dias_funcionamento", "1,2,3,4,5,6"),
        ]
        with conn.cursor() as cur:
            cur.executemany(
                "INSERT INTO configuracao (chave, valor) VALUES (%s, %s) ON CONFLICT (chave) DO NOTHING",
                configuracoes,
            )


def obter_configuracao(conn, chave):
    """Obtém um valor de configuração do banco."""
    row = conn.execute(
        "SELECT valor FROM configuracao WHERE chave = %s", (chave,)
    ).fetchone()
    return row["valor"] if row else None


def obter_todas_configuracoes(conn):
    """Obtém todas as configurações como dicionário."""
    rows = conn.execute("SELECT chave, valor FROM configuracao").fetchall()
    return {row["chave"]: row["valor"] for row in rows}


def atualizar_configuracao(conn, chave, valor):
    """Atualiza ou insere uma configuração."""
    conn.execute(
        """
        INSERT INTO configuracao (chave, valor) VALUES (%s, %s)
        ON CONFLICT (chave) DO UPDATE SET valor = EXCLUDED.valor
        """,
        (chave, valor),
    )
    _incrementar_versao_configuracoes(conn)


def atualizar_configuracoes(conn, configuracoes):
    """Atualiza múltiplas configurações de uma vez."""
    with conn.cursor() as cur:
        cur.executemany(
            """
            INSERT INTO configuracao (chave, valor) VALUES (%s, %s)
            ON CONFLICT (chave) DO UPDATE SET valor = EXCLUDED.valor
            """,
            list(configuracoes.items()),
        )
    _incrementar_versao_configuracoes(conn)


def _incrementar_versao_configuracoes(conn):
    conn.execute(
        """
        INSERT INTO configuracao (chave, valor)
        VALUES (%s, '1')
        ON CONFLICT (chave) DO UPDATE
        SET valor = (configuracao.valor::BIGINT + 1)::TEXT
        """,
        (CONFIG_CACHE_VERSION_KEY,),
    )


def admin_precisa_alterar_senha(conn, usuario):
    """Verifica se o admin precisa concluir a configuração inicial (primeiro acesso)."""
    row = conn.execute(
        "SELECT usuario, senha_inicial_alterada, email, nome_responsavel FROM admin WHERE usuario = %s",
        (usuario,),
    ).fetchone()
    if not row:
        return False
    email = (row["email"] or "").strip() if "email" in row and row["email"] else ""
    nome_responsavel = (
        (row["nome_responsavel"] or "").strip()
        if "nome_responsavel" in row and row["nome_responsavel"]
        else ""
    )
    return (
        (not row["senha_inicial_alterada"])
        or (not email)
        or (not nome_responsavel)
        or (row["usuario"] == "admin")
    )


def admin_concluir_primeiro_acesso(
    conn,
    usuario_atual,
    novo_login,
    nova_senha,
    email,
    nome_responsavel,
    nome_estabelecimento,
):
    """Conclui a configuração inicial do primeiro acesso de forma atômica."""
    from werkzeug.security import generate_password_hash

    row = conn.execute(
        "SELECT id, usuario, senha_hash, senha_inicial_alterada FROM admin WHERE usuario = %s",
        (usuario_atual,),
    ).fetchone()
    if not row:
        return False, "Usuário não encontrado."

    # Verifica se novo_login já está em uso por outro registro
    login_existente = conn.execute(
        "SELECT id FROM admin WHERE LOWER(usuario) = LOWER(%s) AND id != %s",
        (novo_login, row["id"]),
    ).fetchone()
    if login_existente:
        return False, "O login informado já está em uso."

    novo_hash = generate_password_hash(nova_senha)

    conn.execute(
        """
        UPDATE admin
        SET usuario = %s,
            senha_hash = %s,
            senha_inicial_alterada = TRUE,
            email = %s,
            nome_responsavel = %s
        WHERE id = %s
        """,
        (novo_login, novo_hash, email, nome_responsavel, row["id"]),
    )

    atualizar_configuracao(conn, "nome_estabelecimento", nome_estabelecimento)

    return True, None


def admin_alterar_senha(conn, usuario, senha_atual, nova_senha):
    """Altera a senha do admin validando a senha atual."""
    from werkzeug.security import check_password_hash, generate_password_hash

    row = conn.execute(
        "SELECT id, senha_hash, senha_inicial_alterada FROM admin WHERE usuario = %s",
        (usuario,),
    ).fetchone()
    if not row:
        return False, "Usuário não encontrado."

    if not check_password_hash(row["senha_hash"], senha_atual):
        return False, "Senha atual incorreta."

    if senha_atual == nova_senha:
        return False, "A nova senha deve ser diferente da senha atual."

    novo_hash = generate_password_hash(nova_senha)
    conn.execute(
        """
        UPDATE admin
        SET senha_hash = %s, senha_inicial_alterada = TRUE
        WHERE id = %s
        """,
        (novo_hash, row["id"]),
    )
    return True, None


def obter_admin_por_email(conn, email):
    """Busca admin pelo e-mail de recuperação cadastrado na conta."""
    if not email:
        return None
    return conn.execute(
        "SELECT id, usuario, email, nome_responsavel FROM admin WHERE LOWER(email) = LOWER(%s)",
        (email.strip(),),
    ).fetchone()


def criar_token_recuperacao(conn, admin_id, token_hash, expira_em):
    """Salva o hash do token de recuperação com prazo de expiração de 30 min."""
    conn.execute(
        """
        INSERT INTO admin_token_recuperacao (admin_id, token_hash, expira_em, usado)
        VALUES (%s, %s, %s, FALSE)
        """,
        (admin_id, token_hash, expira_em),
    )


def validar_token_recuperacao(conn, token_hash):
    """Valida se o token de recuperação existe, não foi usado e não expirou."""
    from datetime import datetime, timezone

    row = conn.execute(
        """
        SELECT t.id, t.admin_id, t.expira_em, t.usado, a.usuario, a.email
        FROM admin_token_recuperacao t
        JOIN admin a ON a.id = t.admin_id
        WHERE t.token_hash = %s
        """,
        (token_hash,),
    ).fetchone()

    if not row:
        return False, "Link de recuperação inválido.", None

    if row["usado"]:
        return False, "Este link de recuperação já foi utilizado.", None

    agora = datetime.now(timezone.utc)
    expira_em = row["expira_em"]
    if expira_em.tzinfo is None:
        expira_em = expira_em.replace(tzinfo=timezone.utc)

    if expira_em < agora:
        return False, "Este link de recuperação expirou.", None

    return True, None, row


def redefinir_senha_com_token(conn, token_hash, nova_senha):
    """Redefine a senha do admin e invalida o token de uso único de forma atômica."""
    from werkzeug.security import generate_password_hash

    valido, erro, row = validar_token_recuperacao(conn, token_hash)
    if not valido:
        return False, erro

    novo_hash = generate_password_hash(nova_senha)

    conn.execute(
        "UPDATE admin_token_recuperacao SET usado = TRUE WHERE id = %s",
        (row["id"],),
    )
    conn.execute(
        "UPDATE admin SET senha_hash = %s, senha_inicial_alterada = TRUE WHERE id = %s",
        (novo_hash, row["admin_id"]),
    )
    return True, None


def atualizar_agendamentos_realizados(conn):
    conn.execute(
        """
        UPDATE agendamento
        SET status = 'realizado'
        WHERE status = 'agendado'
          AND data::date < CURRENT_DATE
        """
    )


def seed_data(conn):
    count_servicos = conn.execute(
        "SELECT COUNT(*) AS c FROM servico"
    ).fetchone()["c"]

    if count_servicos == 0:
        with conn.cursor() as cur:
            cur.executemany(
                "INSERT INTO servico (nome, preco, duracao_minutos) VALUES (%s, %s, %s)",
                [
                    ("Corte", 40.0, 30),
                    ("Barba", 35.0, 30),
                    ("Corte + Barba", 70.0, 60),
                ],
            )

    count_profissionais = conn.execute(
        "SELECT COUNT(*) AS c FROM profissional"
    ).fetchone()["c"]

    if count_profissionais == 0:
        with conn.cursor() as cur:
            cur.executemany(
                "INSERT INTO profissional (nome, ativo) VALUES (%s, TRUE)",
                [("Carlos",), ("Rafael",)],
            )

    count_admin = conn.execute(
        "SELECT COUNT(*) AS c FROM admin"
    ).fetchone()["c"]

    if count_admin == 0:
        from werkzeug.security import generate_password_hash

        senha_inicial = os.environ.get("ADMIN_SENHA_INICIAL")
        if not senha_inicial:
            raise RuntimeError(
                "ADMIN_SENHA_INICIAL não definida. "
                "Defina a variável de ambiente ADMIN_SENHA_INICIAL para criar o usuário admin inicial."
            )
        conn.execute(
            "INSERT INTO admin (usuario, senha_hash, senha_inicial_alterada) VALUES (%s, %s, FALSE)",
            ("admin", generate_password_hash(senha_inicial)),
        )
