import os
from contextlib import contextmanager

import psycopg
from psycopg.rows import dict_row


def get_connection():
    return psycopg.connect(
        host=os.environ["POSTGRES_HOST"],
        port=os.environ["POSTGRES_PORT"],
        dbname=os.environ["POSTGRES_DB"],
        user=os.environ["POSTGRES_USER"],
        password=os.environ["POSTGRES_PASSWORD"],
        row_factory=dict_row,
    )


@contextmanager
def db_session():
    conn = get_connection()
    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def init_db():
    with db_session() as conn:
        # Serializa a inicialização para evitar corrida entre workers.
        conn.execute("SELECT pg_advisory_lock(314159265358979)")
        conn.execute("""
            CREATE TABLE IF NOT EXISTS servico (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nome TEXT NOT NULL,
                preco NUMERIC(10, 2) NOT NULL,
                duracao_minutos INTEGER NOT NULL
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS profissional (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nome TEXT NOT NULL,
                ativo BOOLEAN NOT NULL DEFAULT TRUE
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS agendamento (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                cliente_nome TEXT NOT NULL,
                cliente_telefone TEXT NOT NULL,
                servico_id INTEGER NOT NULL,
                profissional_id INTEGER NOT NULL,
                data TEXT NOT NULL,
                hora TEXT NOT NULL,
                criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (servico_id) REFERENCES servico(id),
                FOREIGN KEY (profissional_id) REFERENCES profissional(id)
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS agendamento_servico (
                agendamento_id INTEGER NOT NULL,
                servico_id INTEGER NOT NULL,
                PRIMARY KEY (agendamento_id, servico_id),
                FOREIGN KEY (agendamento_id) REFERENCES agendamento(id) ON DELETE CASCADE,
                FOREIGN KEY (servico_id) REFERENCES servico(id)
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS admin (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                usuario TEXT NOT NULL UNIQUE,
                senha_hash TEXT NOT NULL
            )
        """)

        # Compatibilidade com bancos existentes: adiciona o status sem perder dados.
        conn.execute("""
            ALTER TABLE agendamento
            ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'agendado'
        """)

        # Migra a relação legada de serviço único para a nova relação.
        conn.execute("""
            INSERT INTO agendamento_servico (agendamento_id, servico_id)
            SELECT id, servico_id
            FROM agendamento
            WHERE servico_id IS NOT NULL
            ON CONFLICT (agendamento_id, servico_id) DO NOTHING
        """)

        atualizar_agendamentos_realizados(conn)
        seed_data(conn)


def atualizar_agendamentos_realizados(conn):
    conn.execute(
        """
        UPDATE agendamento
        SET status = 'realizado'
        WHERE status = 'agendado'
          AND data::date < CURRENT_DATE
        """
    )


def seed_data(conn):
    count_servicos = conn.execute(
        "SELECT COUNT(*) AS c FROM servico"
    ).fetchone()["c"]

    if count_servicos == 0:
        with conn.cursor() as cur:
            cur.executemany(
                "INSERT INTO servico (nome, preco, duracao_minutos) VALUES (%s, %s, %s)",
                [
                    ("Corte", 40.0, 30),
                    ("Barba", 35.0, 30),
                    ("Corte + Barba", 70.0, 60),
                ],
            )

    count_profissionais = conn.execute(
        "SELECT COUNT(*) AS c FROM profissional"
    ).fetchone()["c"]

    if count_profissionais == 0:
        with conn.cursor() as cur:
            cur.executemany(
                "INSERT INTO profissional (nome, ativo) VALUES (%s, TRUE)",
                [("Carlos",), ("Rafael",)],
            )

    count_admin = conn.execute(
        "SELECT COUNT(*) AS c FROM admin"
    ).fetchone()["c"]

    if count_admin == 0:
        from werkzeug.security import generate_password_hash

        conn.execute(
            "INSERT INTO admin (usuario, senha_hash) VALUES (%s, %s)",
            ("admin", generate_password_hash("barbeariatop123")),
        )
