import os
from contextlib import contextmanager

import psycopg
from psycopg.rows import dict_row


def get_connection():
    return psycopg.connect(
        host=os.environ["POSTGRES_HOST"],
        port=os.environ["POSTGRES_PORT"],
        dbname=os.environ["POSTGRES_DB"],
        user=os.environ["POSTGRES_USER"],
        password=os.environ["POSTGRES_PASSWORD"],
        row_factory=dict_row,
    )


@contextmanager
def db_session():
    conn = get_connection()
    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def init_db():
    with db_session() as conn:
        # Serializa a inicialização para evitar corrida entre workers.
        conn.execute("SELECT pg_advisory_lock(314159265358979)")
        conn.execute("""
            CREATE TABLE IF NOT EXISTS configuracao (
                chave TEXT PRIMARY KEY,
                valor TEXT NOT NULL
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS servico (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nome TEXT NOT NULL,
                preco NUMERIC(10, 2) NOT NULL,
                duracao_minutos INTEGER NOT NULL
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS profissional (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nome TEXT NOT NULL,
                ativo BOOLEAN NOT NULL DEFAULT TRUE
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS agendamento (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                cliente_nome TEXT NOT NULL,
                cliente_telefone TEXT NOT NULL,
                servico_id INTEGER NOT NULL,
                profissional_id INTEGER NOT NULL,
                data TEXT NOT NULL,
                hora TEXT NOT NULL,
                criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (servico_id) REFERENCES servico(id),
                FOREIGN KEY (profissional_id) REFERENCES profissional(id)
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS agendamento_servico (
                agendamento_id INTEGER NOT NULL,
                servico_id INTEGER NOT NULL,
                PRIMARY KEY (agendamento_id, servico_id),
                FOREIGN KEY (agendamento_id) REFERENCES agendamento(id) ON DELETE CASCADE,
                FOREIGN KEY (servico_id) REFERENCES servico(id)
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS admin (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                usuario TEXT NOT NULL UNIQUE,
                senha_hash TEXT NOT NULL,
                senha_inicial_alterada BOOLEAN NOT NULL DEFAULT FALSE
            )
        """)

        # Compatibilidade com bancos existentes: adiciona o status sem perder dados.
        conn.execute("""
            ALTER TABLE agendamento
            ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'agendado'
        """)

        # Compatibilidade: adiciona coluna senha_inicial_alterada se não existir.
        conn.execute("""
            ALTER TABLE admin
            ADD COLUMN IF NOT EXISTS senha_inicial_alterada BOOLEAN NOT NULL DEFAULT FALSE
        """)

        # Migra a relação legada de serviço único para a nova relação.
        conn.execute("""
            INSERT INTO agendamento_servico (agendamento_id, servico_id)
            SELECT id, servico_id
            FROM agendamento
            WHERE servico_id IS NOT NULL
            ON CONFLICT (agendamento_id, servico_id) DO NOTHING
        """)

        seed_configuracao_padrao(conn)
        atualizar_agendamentos_realizados(conn)
        seed_data(conn)


def seed_configuracao_padrao(conn):
    """Insere configurações padrão apenas se a tabela estiver vazia."""
    count = conn.execute("SELECT COUNT(*) AS c FROM configuracao").fetchone()["c"]
    if count == 0:
        from datetime import time
        configuracoes = [
            ("nome_estabelecimento", "AllLogic Scheduler"),
            ("telefone_estabelecimento", ""),
            ("endereco_estabelecimento", ""),
            ("nome_publico", "AllLogic Scheduler"),
            ("dias_antecedencia_agendamento", "14"),
            ("horario_abertura", "09:00"),
            ("horario_fechamento", "19:00"),
            ("intervalo_slot_minutos", "30"),
            ("dias_funcionamento", "0,1,2,3,4,5"),
        ]
        with conn.cursor() as cur:
            cur.executemany(
                "INSERT INTO configuracao (chave, valor) VALUES (%s, %s) ON CONFLICT (chave) DO NOTHING",
                configuracoes,
            )


def obter_configuracao(conn, chave):
    """Obtém um valor de configuração do banco."""
    row = conn.execute(
        "SELECT valor FROM configuracao WHERE chave = %s", (chave,)
    ).fetchone()
    return row["valor"] if row else None


def obter_todas_configuracoes(conn):
    """Obtém todas as configurações como dicionário."""
    rows = conn.execute("SELECT chave, valor FROM configuracao").fetchall()
    return {row["chave"]: row["valor"] for row in rows}


def atualizar_configuracao(conn, chave, valor):
    """Atualiza ou insere uma configuração."""
    conn.execute(
        """
        INSERT INTO configuracao (chave, valor) VALUES (%s, %s)
        ON CONFLICT (chave) DO UPDATE SET valor = EXCLUDED.valor
        """,
        (chave, valor),
    )


def atualizar_configuracoes(conn, configuracoes):
    """Atualiza múltiplas configurações de uma vez."""
    with conn.cursor() as cur:
        cur.executemany(
            """
            INSERT INTO configuracao (chave, valor) VALUES (%s, %s)
            ON CONFLICT (chave) DO UPDATE SET valor = EXCLUDED.valor
            """,
            list(configuracoes.items()),
        )


def admin_precisa_alterar_senha(conn, usuario):
    """Verifica se o admin precisa alterar a senha inicial (primeiro acesso)."""
    row = conn.execute(
        "SELECT senha_inicial_alterada FROM admin WHERE usuario = %s", (usuario,)
    ).fetchone()
    if not row:
        return False
    return not row["senha_inicial_alterada"]


def admin_alterar_senha(conn, usuario, senha_atual, nova_senha):
    """Altera a senha do admin validando a senha atual."""
    from werkzeug.security import check_password_hash, generate_password_hash

    row = conn.execute(
        "SELECT senha_hash, senha_inicial_alterada FROM admin WHERE usuario = %s", (usuario,)
    ).fetchone()
    if not row:
        return False, "Usuário não encontrado."

    if not check_password_hash(row["senha_hash"], senha_atual):
        return False, "Senha atual incorreta."

    novo_hash = generate_password_hash(nova_senha)
    conn.execute(
        "UPDATE admin SET senha_hash = %s, senha_inicial_alterada = TRUE WHERE usuario = %s",
        (novo_hash, usuario),
    )
    return True, None


def atualizar_agendamentos_realizados(conn):
    conn.execute(
        """
        UPDATE agendamento
        SET status = 'realizado'
        WHERE status = 'agendado'
          AND data::date < CURRENT_DATE
        """
    )


def seed_data(conn):
    count_servicos = conn.execute(
        "SELECT COUNT(*) AS c FROM servico"
    ).fetchone()["c"]

    if count_servicos == 0:
        with conn.cursor() as cur:
            cur.executemany(
                "INSERT INTO servico (nome, preco, duracao_minutos) VALUES (%s, %s, %s)",
                [
                    ("Corte", 40.0, 30),
                    ("Barba", 35.0, 30),
                    ("Corte + Barba", 70.0, 60),
                ],
            )

    count_profissionais = conn.execute(
        "SELECT COUNT(*) AS c FROM profissional"
    ).fetchone()["c"]

    if count_profissionais == 0:
        with conn.cursor() as cur:
            cur.executemany(
                "INSERT INTO profissional (nome, ativo) VALUES (%s, TRUE)",
                [("Carlos",), ("Rafael",)],
            )

    count_admin = conn.execute(
        "SELECT COUNT(*) AS c FROM admin"
    ).fetchone()["c"]

    if count_admin == 0:
        from werkzeug.security import generate_password_hash

        senha_inicial = os.environ.get("ADMIN_SENHA_INICIAL")
        if not senha_inicial:
            raise RuntimeError(
                "ADMIN_SENHA_INICIAL não definida. "
                "Defina a variável de ambiente ADMIN_SENHA_INICIAL para criar o usuário admin inicial."
            )
        conn.execute(
            "INSERT INTO admin (usuario, senha_hash, senha_inicial_alterada) VALUES (%s, %s, FALSE)",
            ("admin", generate_password_hash(senha_inicial)),
        )
